#Set the base image to download content from

FROM python:3.10-slim

#Set the Working directory in Container

WORKDIR /app

#Copy code from host to container

COPY app.py .

#Run the first command to execute in container when it starts

CMD ["python","app.py"]